forge "https://forgeapi.puppetlabs.com"

####################### NOTE #############################
# All modules *must* be pinned to a specific version/tag #
##########################################################

mod 'nubis/nubis_configuration',
    :git => 'https://github.com/gozer/nubis-puppet-configuration.git',
    :ref => 'issue/30/recurse'
